### ISSUE TITLE
Requested changes to GeoNetwork 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#100]
The client is requesting few changes to the new GN 3 RNDT installed in the new SDI.

From the client:

>Per quanto riguarda l'interfaccia, invece avremmo la necessità di due migliorie che sono:

>- Nella pagina di ricerca dei dataset, tra i filtraggi aggiungere un filtro che consente di estrarre i risultati in base ad un range di "Data di pubblicazione" (filtrare tutti i dataset con Data di pubblicazione da gg/mm/aaaa a gg/mm/aaaa)

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/c5674621-bc26-41ed-bf88-93d63505bcf9)

>- Nel pdf che è possibile esportare dopo aver selezionato i dataset eliminare i seguenti campi:
>   - Update frequency
>   - Record updated
>   - Risorse
>   - More onlineinformation

>Quindi gli unici campi visibili dovranno esssere:
>   - Descrizione
>   - Estensione
>   - Parole chiave
>   - Access and useconstraints
>   - Data type
>   - Format
>   - Identificatoreunivoco

![image](https://user-images.githubusercontent.com/1280027/155680936-3c48df42-c541-4c2a-99be-a32bc5f18728.png)

**Comment by tdipisa** [comment]
@etj we need an estimate for this

**Comment by etj** [comment]
Il filtro temporale già esiste, basta premere l'hamburger button accanto alla barra di ricerca:

![image](https://user-images.githubusercontent.com/717359/156137277-8fc7ab06-6e0f-4c5b-94d7-fde73b153a1b.png)

**Comment by tdipisa** [comment]
No longer needed for the client now
