### ISSUE TITLE
Redirect issue?

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#106]
From the client:

>come ti dicevo poco fa durante la call, ieri @Foresta Francesco mi chiese di sottoporvi il problema che ha riscontrato dopo aver fatto il vitrualhost geoserver.comune.intranet.conf sulla macchina sr-vm333-sitpub.comune.intranet:
```
<VirtualHost *:80>

    ProxyPass           /geoserver        http://sr-vm380-sitgs1.comune.intranet:7080/geoserver
    ProxyPassReverse    /geoserver        http://sr-vm380-sitgs1.comune.intranet:7080/geoserver

    ProxyPass           /        http://sr-vm380-sitgs1.comune.intranet:7080/geoserver
    ProxyPassReverse    /        http://sr-vm380-sitgs1.comune.intranet:7080/geoserver

    ServerName       geoserver.comune.intranet
    ServerAlias      geoserver geoserver.*
    DirectoryIndex index.html index.php

    ErrorLog         logs/geoserver/error_log
    CustomLog        logs/geoserver/access_log combined

</VirtualHost>
<VirtualHost *:7080>
    ServerName geoserver.comune.intranet
    ServerAlias geoserver.comune.intranet

    Redirect permanent / http://geoserver.comune.intranet
</VirtualHost>
```

>Ovvero, succede questo:
quando puntiamo a http//geoserver.comune.intranet veniamo giustamente direzionati sulla web-console dell'istanza master del geoserver sitgs1 ( http://sr-vm380-sitgs1.comune.intranet:7080/geoserver ) ma una volta che, da questa, facciamo il Login il browser presenta nuovamente nella URL il nome macchina del server:
http://sr-vm380-sitgs1.comune.intranet:7080/geoserver/web/  , non mantenendo il nome assegnatogli tramite il VirtualHost.
Perché ?

**Comment by lpasquali** [comment]
@randomorder @tdipisa adding Global Proxy url this is fixed but then we should rewrite such url for the slaves upon sync from master, 
other way is to configure headers for apache reverse proxy so we can let geoserver respond as whatever balancer calls it, this way configuration would be identical on master and slaves for global proxy url at the moment is not working, apache does not forward the headers.
for the moment I added the hostname in global proxy url, so it is working
