### ISSUE TITLE
download shapefile from datigis.comune.intranet sometimes is corrupted for some layers

### ISSUE THREAD

**Issue by lpasquali** [geosolutions-it/MapStore2-C027#108]
check why shapefile download gives corrupted zip file on second gs1 instance.
Example of issue:

|works or not| URL on single instance |
|:----------------|:---------------------------------|
|OK|http://sr-vm380-sitgs1.comune.intranet:8080/geoserver/istruzione/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=istruzione:alunni_civici_eta_resid&outputFormat=SHAPE-ZIP|
|KO|http://sr-vm380-sitgs1.comune.intranet:9080/geoserver/istruzione/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=istruzione:alunni_civici_eta_resid&outputFormat=SHAPE-ZIP|
|OK|http://sr-vm380-sitgs1:8080/geoserver/catastoreti/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=catastoreti:access_point_wifi&outputFormat=SHAPE-ZIP|
|KO|http://sr-vm380-sitgs1:9080/geoserver/catastoreti/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=catastoreti:access_point_wifi&outputFormat=SHAPE-ZIP|

**Comment by lpasquali** [comment]
one more layer affected:
- mobilita:colonnine_enel

**Comment by lpasquali** [comment]
@tdipisa @randomorder 

the shapefile which derives from a sql view changed since the restart of geoserver2 which fixed the problem momentarily
diff ../today/access_point_wifiPoint.dbf ../yesterday/access_point_wifiPoint.dbf 
Binary files ../file1/access_point_wifiPoint.dbf and ../Downloads/access_point_wifiPoint.dbf differ

This means they change postgres data and do not restart both geoserver instances, creating misalignment.

**Comment by randomorder** [comment]
moving back to ready. @lpasquali please get in touch with client asking for :
- a dump of the three interested tables as of today
- a copy of the datadit as of today
- when the same problem happens again get another dump and copy of datadir and send them over to us for investigation

**Comment by lpasquali** [comment]
@randomorder I have yet to find a solution but I found to new pieces of information.

Using this script:
```python
#!/usr/bin/python
from xml.dom import minidom
import sys

geoserver = sys.argv[1]
port = sys.argv[2]
dom = minidom.parse('getcapabilities-wfs.xml')
elements = dom.getElementsByTagName('Name')

for element in elements:
    layer = element.firstChild.data
    command = ('curl -o %s/%s_%s.zip -LO \'http://%s:%s/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=%s&outputFormat=SHAPE-ZIP\' && sleep 1') % (port,layer,port,geoserver,port,layer)
    print(command)
```
I construct a command list which downloads any possible shapefile.
The result is that *all* shapefiles are broken not just some: 719 layers served by wfs are not working right now on master.

I was told several times that cascading layers in geoserver are "always bad" and confusing, creating issues elsewhere when not working properly.

I checked external layers, there are some, this is not reachable it seems:
 
http://geoserver.055055.it/geoserver/silfi_rete/ows?service=wfs&version=1.0.0&request=GetCapabilities


from the command line of sr-vm380-sitgs1 (new geoserver) if I do not have the proxy in my bash environment I get redirected to an html page with this content:

![Screenshot from 2022-04-20 16-11-18](https://user-images.githubusercontent.com/1780406/164250057-4d241e70-7f42-4037-9ba1-dec96a3fcbe3.png)

if I add the http proxy to bash environment the request remains stuck, the three layers depending on this store are not working as well, for example:

http://geoserver.comune.intranet/geoserver/silfi/wms?service=WMS&version=1.1.0&request=GetMap&layers=silfi%3AND_ELE_070302_id&bbox=6931000.0%2C4835700.0%2C6947500.0%2C4849500.0&width=768&height=642&srs=EPSG%3A6875&styles=&format=application/openlayers

Oddly the error returned from the cascading layer is the same of shapefile.
More over, only shapefile-zip output format is affected, any other kind of outputformat is working fine.

concerning the fact that restart "solves" the shapefile download, is it possible that shapefiles download is broken only after such cascading layers are requested at a certain point in time after the reload?

So for now the only true anomaly that should be fixed (by firenze sysadmins) should be the cascading layers, I am checking all of them, as some wortk fine.

**Comment by lpasquali** [comment]
@randomorder what if to mitigate (problem would appear solved by the eyes of customer) I use the error to issue geoserver restart through watchdog upon necessity? 
this way we can map the happening of the issue and its fixing timings

**Comment by lpasquali** [comment]
as discussed with @randomorder for now adding logic to the watchdog is the better way to go
for now

**Comment by randomorder** [comment]
looking at the log I suspect the java temp dir (which would be the temporary directory in which the shapefiles are created before uploading them to the end user) is being BRASATA on a periodic bas

We can try to just explicitly change the path to a well known location @tdipisa

**Comment by tdipisa** [comment]
Thank you @randomorder and @lpasquali, Please continue to keep me updated on this. Thank you.

**Comment by lpasquali** [comment]
@randomorder I think the fix is enough, the issue started because they are using "containered" tmp directories for some services (geomaster,geoserver2) while geoserver used real  /tmp dir before you changed for all the instances to $CATALINA_BASE/temp
I see that files are created correctly. 
the three services anyway are misaligned in terms of configuration:
```
root@sr-vm380-sitgs1:~# systemctl show geomaster geoserver geoserver2 | egrep '^(ReadWritePaths|After|RequiresMountsFor)' 
ReadWritePaths=/var/lib/geomaster/conf/Catalina /var/lib/geomaster/webapps /var/lib/geomaster/temp /var/log/geomaster /opt/data
After=systemd-journald.socket systemd-tmpfiles-setup.service system.slice sysinit.target basic.target -.mount systemd-remount-fs.service network.target
RequiresMountsFor=/tmp /var/tmp /var/lib/geomaster /var/cache/geomaster /var/log/geomaster
ReadWritePaths=/etc/tomcat9/Catalina /var/lib/tomcat9/webapps /var/log/tomcat9 /var/lib/tomcat9/temp /tmp /opt/data
After=sysinit.target systemd-remount-fs.service network.target systemd-journald.socket system.slice -.mount basic.target
RequiresMountsFor=/var/log/tomcat9 /var/cache/tomcat9 /var/lib/tomcat9
ReadWritePaths=/tmp /var/lib/geoserver2/conf/Catalina /var/lib/geoserver2/temp /var/lib/geoserver2/webapps /var/log/geoserver2 /opt/data
After=system.slice -.mount network.target systemd-remount-fs.service systemd-journald.socket sysinit.target systemd-tmpfiles-setup.service basic.target
RequiresMountsFor=/var/tmp /var/log/geoserver2 /tmp /var/lib/geoserver2 /var/cache/geoserver2
root@sr-vm380-sitgs1:~# 
```
should we report this misalignment even if I believe the fix by @randomorder is definitive for shapefile? @randomorder @tdipisa

**Comment by lpasquali** [comment]
I aligned both sitgs1 and sitgs2 servers with temp dir inside the $CATALINA_BASE
Examination of watchdog logsmade me able to track down the manifestation of the problem (on geoserver2 and geomaster) at a precise hour for sitgs1 and geomaster/geoserver2 
```
Fri 22 Apr 2022 06:50:01 AM CEST WatchDog Status: FAIL -> geomaster is NOT responding properly at URL 
```
but I also see the mitigation watchdog was doing its job since it was started.
I think we have fixed the issue once and for all changing temp dir of each tomcat instance

**Comment by tdipisa** [comment]
Thank you @lpasquali. Please report back to the client by explaining the cause of the issue and what we have done to fix it. Then please update the documentation accordingly, thank you so much.

Should we disable then the watchdogs you have put in place for this investigation?

**Comment by lpasquali** [comment]
@tdipisa concerning watchdogs not for now, they do nothing if there is no issue, I would leave them on sitgs1 to be sure in case of system upgrades introducing back the issue.

**Comment by tdipisa** [comment]
ok, make sense. In this case please ensure to include them in the documentation.

**Comment by lpasquali** [comment]
documentation updated, https://docs.google.com/document/d/1i5opU9ptqtiG7uyTV2ezHc9stYek5A1DpeuZrGnZBLE/edit#
