### ISSUE TITLE
Misalignment in JNDI Contexts

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#109]
The client reported vie email a misalignment of the JNDI context defined in Tomcat.
Basically, the context.xml file inside the new geoserver machine is from August 2021, with a date prior to the context.xml that was reported, from the sitgn1 machine (old geoserver)

![unnamed.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/d34e610b-70fc-4b8c-9f68-33e02f1a3b03)

Below are also highlighted some syntax discrepancies between the two files, as shown in the image.

![unnamed.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/1224dd29-9a87-4df3-959b-0f52061f8d29)

On the left you can see the context.xml of the sitgn1 machine (of February 2022), while on the right the context.xml of the new sitgs1 machine machine (the one with date August 2021).

**Comment by lpasquali** [comment]
@randomorder  @tdipisa I added the missing jndi (picture one) in context.xml
concerning other screenshot is the needed upgrade to new tomcat version, where some options of jndi were deprecated, changed name

**Comment by randomorder** [comment]
please link the updated docs here

**Comment by lpasquali** [comment]
I did not have a context.xml on the documents because it is quite huge (it would take two pages or three @randomorder
 shoud I add content of context.xml for the geoservers?

**Comment by randomorder** [comment]
no, that's fine thanks
