### ISSUE TITLE
Kibana is not working

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#110]
The client reported by email that the Kibana after the switch over production is not working anymore. We need to access the system and check why.

**Comment by tdipisa** [comment]
@lpasquali it seems to me you haven't reported back to the client the resolution of this. Isn't it?

**Comment by lpasquali** [comment]
@tdipisa I replied the related mail from Geri explaining we are not experiencing such problem anymore.
