### ISSUE TITLE
Layers with wrong Tile matrix aren't visible and they could cause application malfunctionality

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2-C027#14]
Layers with `SPHMERC_900913_world_custom` could cause this issue because resolutions aren't correctly assigned.
Workaround could be to remove duplicated resolutions generated client side to avoid crash from application but layer still will not be visible.

eg. layer `pianificazione:v_ru_timewms_riassetto_rete_at_area_metrop_fi_adottato`

**Comment by tdipisa** [comment]
out of date, closing
