### ISSUE TITLE
Supporto LDAP - MS2

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#17]
At the moment the MapStore's LDAP support does not allow to read users within nested groups. By implementing this feature in MapStore, GS, and GF there will be the possibility to set auth rules with greater granularity in GF; however the possibility to authenticate users within nested domain groups in LDAP should be allowed in MS.

The current configuration deployed in the client's infrastructure is composed by MapStore, GeoServer and GeoFence independently connected to  the same LDAP path with the same configuration. The authentications GeoServer side for OGC requests are managed through Authkey generated by MapStore.

The client's MS version is the stable 2018.01.xx of 13 Feb 2018, the proposal [here](https://docs.google.com/document/d/1IbKi3dWXvxzVf_sR3iv3HwoJdGJGbrNwqoFKIyz5t0E/edit#heading=h.hpvkr3wxmvs0)

**Comment by mbarto** [comment]
GeoStore support: https://github.com/geosolutions-it/geostore/issues/183

**Comment by Gnafu** [comment]
TODO:
- Build new war
- Deploy

**Comment by Gnafu** [comment]
WIP here: https://docs.google.com/document/d/1pBITHZmDVg2FXnL51G7K6M5fBTb0sxOkenEAAasrB8c/edit#
