### ISSUE TITLE
Supporto LDAP - GeoServer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#18]
Allow in GeoServer the possibility to read LDAP users within a herarchy of nested groups. 

The current configuration deployed in the client's infrastructure is composed by MapStore, GeoServer and GeoFence independently connected to  the same LDAP path with the same configuration. The authentications GeoServer side for OGC requests are managed through Authkey generated by MapStore.

The Client's GS version is 2.13.2, the proposal [here](https://docs.google.com/document/d/1IbKi3dWXvxzVf_sR3iv3HwoJdGJGbrNwqoFKIyz5t0E/edit#heading=h.hpvkr3wxmvs0)

**Comment by simboss** [comment]
@tdipisa translate to english

@nmco this is one of the issues I was talking about

**Comment by Gnafu** [comment]
TODO:
- Get the war from Fernando
- Add the plugins used by client (css)
- Deploy on another tomcat instance
- Test
- Deploy in production

**Comment by Gnafu** [comment]
WIP here: https://docs.google.com/document/d/1pBITHZmDVg2FXnL51G7K6M5fBTb0sxOkenEAAasrB8c/edit#
