### ISSUE TITLE
Supporto LDAP - GeoFence

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#21]
Allow in GeoFence the possibility to read LDAP users within a herarchy of nested groups; rights on GeoServer resources are frequently managed by associating a specific LDAP group or user in the auth rules.

The current configuration deployed in the client's infrastructure is composed by MapStore, GeoServer and GeoFence independently connected to  the same LDAP path with the same configuration. The authentications GeoServer side for OGC requests are managed through Authkey generated by MapStore.

The Client's GF version is 3.1, the proposal [here](https://docs.google.com/document/d/1IbKi3dWXvxzVf_sR3iv3HwoJdGJGbrNwqoFKIyz5t0E/edit#heading=h.hpvkr3wxmvs0)

**Comment by simboss** [comment]
@tdipisa translate to english

@nmco this is one of the issues I was talking about

**Comment by mbarto** [comment]
See https://github.com/geoserver/geofence/issues/119

**Comment by Gnafu** [comment]
TODO:
- Get the updated war from Mauro (or wait an actual release)
- Deploy on a separate tomcat instance
- Test
- Deploy in production

**Comment by Gnafu** [comment]
First test looking good, waiting for the GeoServer/Mapstore2 deploy for an integration test.
WIP here: https://docs.google.com/document/d/1pBITHZmDVg2FXnL51G7K6M5fBTb0sxOkenEAAasrB8c/edit#
