### ISSUE TITLE
Dublin Core Output - Campi aggiuntivi

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#23]
Arricchire/modificare la serializzazione dei metadati in formato DC con i seguenti campi:
- gmd:EX_TemporalExtent
- gmd:topicCategory

Documentazioni:
- Deplopy doc [here](https://docs.google.com/drawings/d/1J6kumZwZdKukWtOy712KKRyt6lz9wYC42yg0hnyD31c/edit)
- GS1 deploy doc [here](https://docs.google.com/document/d/1V9APWf2ycQ7IYqNYN7PnBEvYPgvcODZQJ1uDrReruMM/edit)

**Comment by etj** [comment]
Aggiunto topicaCategory:
```
<dc:subject>environment</dc:subject>
```
ed estensione temporale:
```
<dcterms:temporal>start=2013-01-16; end=2013-01-16</dcterms:temporal>
```
