### ISSUE TITLE
WFS Download

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#25]
Change the WFS download tool configuration to enable it only for authenticated users.

**Comment by simboss** [comment]
this is a customization for this client or a generic change.

If the second option holds I would want to understand the reasoning.

**Comment by simboss** [comment]
@tdipisa hello?

**Comment by tdipisa** [comment]
@simboss this isn't a customization, is a configuration to make the WFS download button enabled only to authenticated users.
