### ISSUE TITLE
Esposizione metadati su MapStore2 e template

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#34]
Per alcuni metadati non risultano visibili in MapStore2 tutti i parametri, in particolare "Riferimenti temporali aggiornamento" e "Bounding Box". Questo comportamento sembrerebbe dipendere dal template utilizzato per metadatare.

Template per servizi: utilizza il tag <srv:extent>

Template per dataset: utilizza il tag <gmd:extent>

Risultano visibili tutti i parametri solo per i dati i metadatati con i template per dataset (<gmd:extent>).
Alcuni dati che puoi prendere come esempio sono: "Infrastrutture di comunicazione elettronica", "Sinistri relativi all’anno 2018", "Cabina di alta tensione".

Si richiede quindi di stimare il tempo necessario a fare le modifiche necessarie per includere tutti i tipi di metadato, sia lato MapStore che lato GeoNetwork

**Comment by etj** [comment]
Initial request:
```
curl 'http://192.168.202.172:8080/geonetwork/srv/ita/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&id=c_d612:666c71bd-b789-4244-abc6-5fb3a14e4ad9'


<?xml version="1.0" encoding="UTF-8"?>
<csw:GetRecordByIdResponse xmlns:csw="http://www.opengis.net/cat/csw/2.0.2">
  <csw:SummaryRecord xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:geonet="http://www.fao.org/geonetwork" xmlns:dct="http://purl.org/dc/terms/">
    <dc:identifier>c_d612:666c71bd-b789-4244-abc6-5fb3a14e4ad9</dc:identifier>
    <dc:title>Infrastrutture di comunicazione elettronica</dc:title>
    <dc:type>service</dc:type>
    <dc:subject>infoMapAccessService</dc:subject>
    <dc:subject>comunicazione</dc:subject>
    <dc:subject>ambiente</dc:subject>
    <dc:subject>antenne</dc:subject>
    <dc:subject>telefonia</dc:subject>
    <dc:subject>infrastrutture</dc:subject>
    <dc:format>OGC:WMC</dc:format>
    <dc:relation />
    <dct:abstract>Georeferenziazione delle infrastrutture di comunicazione elettronica (antenne), impianti radio elettrici (DLgs 259/03).</dct:abstract>
  </csw:SummaryRecord>
</csw:GetRecordByIdResponse>
```

**Comment by etj** [comment]
Initial request with `elementSetName=brief` is ok:

curl 'http://192.168.202.172:8080/geonetwork/srv/ita/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&elementSetName=brief&id=c_d612:666c71bd-b789-4244-abc6-5fb3a14e4ad9'
<?xml version="1.0" encoding="UTF-8"?>
<csw:GetRecordByIdResponse xmlns:csw="http://www.opengis.net/cat/csw/2.0.2">
  <csw:BriefRecord xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:geonet="http://www.fao.org/geonetwork" xmlns:ows="http://www.opengis.net/ows">
    <dc:identifier>c_d612:666c71bd-b789-4244-abc6-5fb3a14e4ad9</dc:identifier>
    <dc:title>Infrastrutture di comunicazione elettronica</dc:title>
    <dc:type>service</dc:type>
    <ows:BoundingBox crs="::">
      <ows:LowerCorner>11.348 43.718</ows:LowerCorner>
      <ows:UpperCorner>11.145 43.84</ows:UpperCorner>
    </ows:BoundingBox>
  </csw:BriefRecord>
</csw:GetRecordByIdResponse

**Comment by etj** [comment]
Fixed output with `elementSetName=full`:

```
curl 'http://192.168.202.172:8080/geonetwork/srv/ita/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&elementSetName=full&id=c_d612:666c71bd-b789-4244-abc6-5fb3a14e4ad9'

<?xml version="1.0" encoding="UTF-8"?>
<csw:GetRecordByIdResponse xmlns:csw="http://www.opengis.net/cat/csw/2.0.2">
  <csw:Record xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:geonet="http://www.fao.org/geonetwork" xmlns:dct="http://purl.org/dc/terms/" xmlns:ows="http://www.opengis.net/ows" xmlns:gml="http://www.opengis.net/gml">
    <dc:identifier>c_d612:666c71bd-b789-4244-abc6-5fb3a14e4ad9</dc:identifier>
    <dc:title>Infrastrutture di comunicazione elettronica</dc:title>
    <dc:type>service</dc:type>
    <dc:subject>infoMapAccessService</dc:subject>
    <dc:subject>comunicazione</dc:subject>
    <dc:subject>ambiente</dc:subject>
    <dc:subject>antenne</dc:subject>
    <dc:subject>telefonia</dc:subject>
    <dc:subject>infrastrutture</dc:subject>
    <dc:format>OGC:WMC</dc:format>
    <dc:contributor>Direzione Ambiente</dc:contributor>
    <dct:abstract>Georeferenziazione delle infrastrutture di comunicazione elettronica (antenne), impianti radio elettrici (DLgs 259/03).</dct:abstract>
    <dc:rights>otherRestrictions</dc:rights>
    <dc:rights>otherRestrictions</dc:rights>
    <dc:relation />
    <dc:format>OGC:WMC</dc:format>
    <ows:BoundingBox crs="urn:ogc:def:crs:EPSG:6.6:4326">
      <ows:LowerCorner>11.348 43.718</ows:LowerCorner>
      <ows:UpperCorner>11.145 43.84</ows:UpperCorner>
    </ows:BoundingBox>
    <dc:URI protocol="OGC:WMS-1.1.1-http-get-map" name="ambiente:infrastrutture_comunicazione_elettronica" description="">http://tms.comune.intranet/geowebcache_internal/service/wms</dc:URI>
  </csw:Record>
</csw:GetRecordByIdResponse>
```

**Comment by tdipisa** [comment]
It seems that temporal extent (dct:temporal) isn't returned for SRV metadata, try the following POST request made by MapStore for metadata '**Infrastrutture di comunicazione elettronica**':

http://sr-vm107-sitgs1.comune.intranet:8080/geonetwork/srv/ita/csw?service=CSW&version=2.0.2&request=GetRecords

`<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:ows="http://www.opengis.net/ows" service="CSW" version="2.0.2" resultType="results" startPosition="1" maxRecords="4"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName><csw:Constraint version="1.1.0"><ogc:Filter><ogc:PropertyIsLike wildCard="%" singleChar="_" escapeChar="\\"><ogc:PropertyName>csw:AnyText</ogc:PropertyName><ogc:Literal>%Infrastrutture di comunicazione elettronica%</ogc:Literal></ogc:PropertyIsLike></ogc:Filter></csw:Constraint></csw:Query></csw:GetRecords>`

Moreover there is an error retrieving the DC metadata through this URL:

http://sr-vm107-sitgs1.comune.intranet:8080/geonetwork/srv/ita/xml_csw-record?id=1094&styleSheet=xml_rndt2dc.xsl

**Comment by etj** [comment]
CSW fixed, now returning also
```
    <dct:temporal>start=2018-01-01; end=2018-01-01</dct:temporal>
```

**Comment by etj** [comment]
xml_rndt2dc.xsl fixed as reported in the deploy doc
