### ISSUE TITLE
Credenziali accesso a GeoNetwork

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#35]
Il comune di Firenze necessita di accesso in lettura al DB di GeoNetwork per eseguire interrogazioni sui contenuti. Le credenziali fornite (presenti nel file config-override.xml di GeoNetwork) non risultano valide. Di seguito la configurazione attualmente utilizzata da GN:

```
       <config>
                    <user>postgres</user>
                    <password>XXXXXX</password>
                    <driver>org.postgis.DriverWrapper</driver>
                    <url>jdbc:postgresql_postGIS://localhost:5432/geonetwork_rndt</url>
                    <poolSize>30</poolSize>
                    <validationQuery>SELECT 1</validationQuery>
       </config>
```

E' necessario:

1. Creare un utente in sola lettura per il DB di GN che il team del Comune di Firenze potrà usare per eseguire le proprie interrogazioni (il file pg_hba.conf di postgresql dovrebbe già essere stato aggiornato da Fabio Carnasciali per consentire accessi da altre macchine, da controllare e aggiornare in base al nuovo utente creato)
2. Sistemare la configurazione di GeoNetwork perchè acceda con un utente dedicato invece che con l'utente **postgres**

Il documento di deploy della macchina su cui è installato GeoNetwork e il DB è reperibile [qui](https://docs.google.com/document/d/1V9APWf2ycQ7IYqNYN7PnBEvYPgvcODZQJ1uDrReruMM/edit#heading=h.45k2z424fnjd).

Il diagramma di deploy dell'infrastruttura è disponibile [qui](https://docs.google.com/drawings/d/1ZqweiPi3JEj8OLYswBbzpW5gIiwV8IORyKwD1BvdLL8/edit).

**Comment by etj** [comment]
https://docs.google.com/document/d/1V9APWf2ycQ7IYqNYN7PnBEvYPgvcODZQJ1uDrReruMM/edit#heading=h.9c8i3s60u8q3
