### ISSUE TITLE
Ricerche da catalogo csw in MapStore2

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#36]
Cercando "alberi" dal catalogo Geonetwork otteniamo infatti 57 risultati (dove sembra sia contenuta la parola 'alberi')

 ![unnamed.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/9680fc0a-30b3-4af5-b997-74858e8ebb58)

Se invece ricerco da catalogo csw di geoserver ottengo solo 4 risultati:

![unnamed.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6032d8e5-3c60-4823-844b-155f7d048c44)

Anche [GeoNetwork](http://192.168.202.172:8080/geonetwork/srv/ita/csw) ritorna 4 metadati facendo una ricerca freetext con la parola 'alberi'

Accedere a [questa mappa di MapStore](http://mapstore2.comune.fi.it/mapstore2/#/viewer/openlayers/1035) dove è possibile effettuare le ricerche (si deve essere in VPN)

**Comment by etj** [comment]
```
<ogc:PropertyIsLike wildCard="%" singleChar="_" escapeChar="\\"><ogc:PropertyName>csw:AnyText</ogc:PropertyName><ogc:Literal>%alberi%</ogc:Literal></ogc:PropertyIsLike>
```
returns 57 records, while
```
<ogc:PropertyIsLike wildCard="%" singleChar="_" escapeChar="\\"><ogc:PropertyName>csw:AnyText</ogc:PropertyName><ogc:Literal>alberi</ogc:Literal></ogc:PropertyIsLike>
```
returns 4

**Comment by etj** [comment]
All of the returned records have a thumbnail link like that
```
<dc:URI protocol="image/png" name="thumbnail">resources.get?id=828&amp;fname=alberi_s.png&amp;access=public</dc:URI>
```

**Comment by etj** [comment]
The returned records are correct.
The errror seems to be the name of the thumbnail resource.
We may remove the thumbnail content from being indexed in the `any` indexed field.
