### ISSUE TITLE
Migration and update of GN1 cluster

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#46]
The current cluster of GeoServer available in [sitgn1](https://docs.google.com/document/d/1cyy-LHIOjKpoUv5mDtO_u-zl2XGvfUU3NtdUyGY6fck/edit#heading=h.hawqmkhlguu5) (current SDI diagram [here](https://docs.google.com/drawings/d/1ZqweiPi3JEj8OLYswBbzpW5gIiwV8IORyKwD1BvdLL8/edit?usp=sharing))  must be migrated to the [new VM](https://docs.google.com/drawings/d/1WD6zANu_jkGFat9zfOXnCyQWQE-bYE4YRAi12bzP6A0/edit) (new name is **sitgs1**) and the version updated to the latest stable 2.19.1 (current version 2.13.2).

The spreadsheet with references to all new VMs is available in drive [here](https://drive.google.com/file/d/1GE7osiWixp_NOF22vUbZJ7Yk-X63c5mw/view?usp=sharing)

The diargam of the new SDI is available [here](https://docs.google.com/drawings/d/1WD6zANu_jkGFat9zfOXnCyQWQE-bYE4YRAi12bzP6A0/edit?usp=sharing)

As part of this issue it is necessary to consider at least:
- [x] Installation of the new GeoServer version in the new environment
- [x] Migration and review of the configuration (GS_DATA_DIR) to the new new instance
- [x] The c027 cluster type is old, we have to provide a master instance

**Comment by lpasquali** [comment]
@randomorder @tdipisa security enhancements by debian/ubuntu needed me to do some additional addition to systemd for tomcat services (this will be documented for each geoserver machine) but I was able to fire up all instances 
2.19.2 with needed plugin is running and connected to new gefence server with former rules which seem to be there correctly, I will test some layers but all stores (postgres and oracle) look like to be correctly in.
diskquota (local geoserver one) was migrated to jndi and looks like to be working fine.

**Comment by tdipisa** [comment]
@lpasquali @randomorder please take into account the third point in description. We should add a master instance of GS but I saw you didn't include it in the new installation.

**Comment by randomorder** [comment]
ComuneFI is going to set up two extra catalina_bases for the masters on the GS1 and GS2

**Comment by tdipisa** [comment]
@lpasquali @randomorder 
I found the following while installing the authkey module on SITGS1

![2021_09_13_14_46_41_Window](https://user-images.githubusercontent.com/1280027/133086893-eeed0822-d178-469a-907e-42bc64cf89ae.png)

@randomorder 
Is probably a general review necessary to check about these things?

**Comment by tdipisa** [comment]
@lpasquali in addition to the above, I've just found that WPS and CSW plugins have not been installed in new GS1 GeoServer

**Comment by randomorder** [comment]
On Friday I noticed with Emanuele the authkey plugin was missing. Please check it's installed

**Comment by lpasquali** [comment]
@randomorder I prepared: 
- created dedicated datadir for geomaster instance
- externalized coverages
- externalized logs (updated filebeat paths)
- scripts to sync bearing smoke tests (tested completely as in every day usage using the old log files to be wiped inside datadir)
- geomaster is configured like other instances with different datadir

I am documenting and splitting informations where needed into Manuale Installazione or Manuale Operativo

**Comment by lpasquali** [comment]
this is following #55 into review
