### ISSUE TITLE
Migration and update of GN2 cluster

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#47]
The current cluster of GeoServer available in [sitgn2](https://docs.google.com/document/d/18ZmLLW3eaa_1SfkDwy77uo938gbddO3ulLLFFXBgKfI/edit#heading=h.hawqmkhlguu5) (current SDI diagram [here](https://docs.google.com/drawings/d/1ZqweiPi3JEj8OLYswBbzpW5gIiwV8IORyKwD1BvdLL8/edit?usp=sharing))  must be migrated to the [new VM](https://docs.google.com/drawings/d/1WD6zANu_jkGFat9zfOXnCyQWQE-bYE4YRAi12bzP6A0/edit) (new name is **sitgs2**) and the version updated to the latest stable 2.19.1 (current version 2.13.2).

The spreadsheet with references to all new VMs is available in drive [here](https://drive.google.com/file/d/1GE7osiWixp_NOF22vUbZJ7Yk-X63c5mw/view?usp=sharing)

The diargam of the new SDI is available [here](https://docs.google.com/drawings/d/1WD6zANu_jkGFat9zfOXnCyQWQE-bYE4YRAi12bzP6A0/edit?usp=sharing)

As part of this issue it is necessary to consider at least:
- [x] Installation of the new GeoServer version in the new environment
- [x] Migration and review of the configuration (GS_DATA_DIR) to the new new instance
- [x] The c027 cluster type is old, we have to provide a master instance

**Comment by lpasquali** [comment]
@randomorder @tdipisa besides diversity in the geospatial data, things worked as in here:
https://github.com/geosolutions-it/MapStore2-C027/issues/46#issuecomment-908310035

**Comment by tdipisa** [comment]
@lpasquali @randomorder please take into account the third point in description. We should add a master instance of GS but I saw you didn't include it in the new installation.

**Comment by tdipisa** [comment]
@lpasquali I've just found that WPS and CSW plugins have not been installed in new GS2 GeoServer. We ned them installed as soon as possible to complete tests.

**Comment by lpasquali** [comment]
@tdipisa enabled WPS and and CS
![Screenshot from 2021-09-20 16-46-59](https://user-images.githubusercontent.com/1780406/134022821-045e56ce-cca7-450b-8bab-313f00a1cbaa.png)
W

**Comment by randomorder** [comment]
On Friday I noticed with Emanuele the authkey plugin was missing. Please check it's installed

**Comment by lpasquali** [comment]
```
root@sr-vm381-sitgs2:~# ls -la /var/lib/geoserver/webapps/geoserver/WEB-INF/lib/*auth*
-rw-r----- 1 tomcat tomcat 82614 Jul 20 05:18 /var/lib/geoserver/webapps/geoserver/WEB-INF/lib/gs-authkey-2.19.2.jar
root@sr-vm381-sitgs2:~# ls -la /var/lib/geoserver2/webapps/geoserver/WEB-INF/lib/*auth*
-rw-r----- 1 tomcat tomcat 82614 Jul 20 05:18 /var/lib/geoserver2/webapps/geoserver/WEB-INF/lib/gs-authkey-2.19.2.jar
root@sr-vm381-sitgs2:~# 
```
@randomorder

**Comment by lpasquali** [comment]
@randomorder I configured the master for both geoserver machines, how should the configuration release flux be? we document to just restart both slaves once happy with master?

**Comment by lpasquali** [comment]
@randomorder since every path was named identically for ease of maintanance on each server everythiong said in this comment [here](https://github.com/geosolutions-it/devops#issuecomment-934165655) applied also for this issue

**Comment by lpasquali** [comment]
this is following #55 into review
