### ISSUE TITLE
Migration and update of GeoWebCache

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#49]
The current GeoWebCache instance available in [sitwc1](https://docs.google.com/document/d/1bm0WtmMRofHrogKryAq_Rq9anzldn2yX2-3vy3tAjbU/edit#heading=h.wzed2timoadg) (current SDI diagram [here](https://docs.google.com/drawings/d/1ZqweiPi3JEj8OLYswBbzpW5gIiwV8IORyKwD1BvdLL8/edit?usp=sharing)) must be migrated to the [new VM](https://docs.google.com/drawings/d/1WD6zANu_jkGFat9zfOXnCyQWQE-bYE4YRAi12bzP6A0/edit) (new name is **sitgwc**) and the version updated to the latest stable version (1.19.1).

The spreadsheet with references to all new VMs is available in drive [here](https://drive.google.com/file/d/1GE7osiWixp_NOF22vUbZJ7Yk-X63c5mw/view?usp=sharing)

The diargam of the new SDI is available [here](https://docs.google.com/drawings/d/1WD6zANu_jkGFat9zfOXnCyQWQE-bYE4YRAi12bzP6A0/edit?usp=sharing)

As part of this issue it is necessary to consider at least:
- [x] Installation of the latest GeoWebCache in the new environment
- [x] Review of the configuration for the new SDI if needed (geowebcache.xml)
- [x] Migration of the existing GWC cache dir

**Comment by randomorder** [comment]
can we close this one @tdipisa ?

**Comment by tdipisa** [comment]
Let's wait for client tests first
