### ISSUE TITLE
Wrong shapefile import

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2-C027#5]
See https://github.com/geosolutions-it/MapStore2/issues/2325

**Comment by mbarto** [comment]
This needs to be merged by the proj4j people to fix this one: https://github.com/proj4js/wkt-parser/pull/6

**Comment by tdipisa** [comment]
waiting for the PR merge we currently use our [fork](https://github.com/geosolutions-it/proj4js/tree/mapstore2_fixes)
