### ISSUE TITLE
Port JDBC driver update to ComuneFI MapStore

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2-C027#54]
Once [this](https://github.com/geosolutions-it/MapStore2/issues/7272) has been merged, port it to ComuneFI

**Comment by tdipisa** [comment]
c027 is currently using geostore 1.6.0
https://github.com/geosolutions-it/MapStore2-C027/blob/master/web/pom.xml#L32

**Comment by mbarto** [comment]
@tdipisa the PostgreSQL driver update is currently available only on master, you can either:
 - backport it to 1.7.x and 1.6.x, or
 - override the jdbc driver version at the C027 project level, directly

**Comment by tdipisa** [comment]
Thank you @mbarto, can you do the second please and raise a PR? Thank you.
