### ISSUE TITLE
Configure GS machines for log stashing in kibana

### ISSUE THREAD

**Issue by lpasquali** [geosolutions-it/MapStore2-C027#56]
- maintain same filebeat version if possible 
- check how to use old indexes and old dashboard.

**Comment by lpasquali** [comment]
@randomorder @tdipisa filebeat is configured on both geoservers, I see there is a filebeat as well for geowebcache (external) and no dashboard in kibana is using it, is still needed to harvest logs from geowebcache on its new instance?

**Comment by lpasquali** [comment]
everything is put in place, I just need to switch on logstash once we migrate to new cluster/services @tdipisa @randomorder

**Comment by randomorder** [comment]
> everything is put in place, I just need to switch on logstash once we migrate to new cluster/services @tdipisa @randomorder

Why not leaving it powered on? It would be a good test

**Comment by tdipisa** [comment]
> > everything is put in place, I just need to switch on logstash once we migrate to new cluster/services @tdipisa @randomorder
> 
> Why not leaving it powered on? It would be a good test

What about this @randomorder ?

**Comment by lpasquali** [comment]
@tdipisa @randomorder the geoserver logs and audit are sent correctly, I see there is something not shipped by filebeat:
```
  file {
    path => "/var/log/comunefi/apache_logs/tms.comune.fi.it/*log"
    start_position => "end"
    type => "apache-gwc"
    tags => [ "comunefi", "gwc", "external" ]
  }

  file {
    path => "/var/log/comunefi/apache_logs/tms.comune.internal/*log"
    start_position => "end"
    type => "apache-gwc"
    tags => [ "comunefi", "gwc", "internal" ]
  }
```
which I think is not synced as it was from the new sitpub server (main balancer) we need to ask customer's sysadmins about this, I see logs were already stopped at 31 march

**Comment by lpasquali** [comment]
One last thought about kibana/elk: @randomorder @tdipisa after last call of yesterday we learned customer has some services which were connecting directly to the old gs instances, not passing through balancer, maybe we should make a logstash-lecacy index so they can have a separated dashboard filled with what is still being requested to old cluster. I need anyway to connect to kibana for some screenshot for documentation, and what I'm proposing would add 10-15 minutes overhead to the documentation operation

**Comment by randomorder** [comment]
ignore for the moment and let's talk about it. It was not agreed

**Comment by tdipisa** [comment]
> ignore for the moment and let's talk about it. It was not agreed

I totally agree with this. Old GS instances will be decommissioned, so we don't need to spend time on this.

**Comment by lpasquali** [comment]
@randomorder @tdipisa ok, I move this in review
