### ISSUE TITLE
MS home loading issue 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#59]
When I access the home after some time, at the first load the MS home has empty content

![2021_09_15_11_10_52_](https://user-images.githubusercontent.com/1280027/133439736-8f0f077c-b6b1-4d2d-9d6f-f599cac42638.png)

So that I have to refresh the page to have contents

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/47fdfe7b-9a9a-484a-81d2-46e51ae6b60d)

**NOTE:**
@randomorder I remember the same problem occurred in the past for another client (probably c098 or c042). It is maybe due to the fact that MS is trying to use an idle connection for some reason?

**Comment by randomorder** [comment]
let's try to reproduce, check the logs andreview the jdbc conn pool next time you work for ComuneFI @lpasquali

**Comment by randomorder** [comment]
I don't see anything useful
Can we validate the connection before using it in GeoStore code maybe @tdipisa ?

**Comment by tdipisa** [comment]
It seems working well until now.
