### ISSUE TITLE
Review of DATA-DIRs paths

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#60]
As per comment [here](https://github.com/geosolutions-it/MapStore2-C027/issues/46#issuecomment-918160659)
![2021_09_13_14_46_41_Window](https://user-images.githubusercontent.com/1280027/133086893-eeed0822-d178-469a-907e-42bc64cf89ae.png)

**Comment by lpasquali** [comment]
I fixed this while doing #56 @tdipisa @randomorder

**Comment by randomorder** [comment]
thanks
