### ISSUE TITLE
WMS GetCapabilities are slow

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#62]
WMS get Capabilities from MS against both GS1 and GS2 geoservers takes more than 30 seconds and the request goes in timeout (proxy.properties sets the timeout to 30s). Why WMS GetCapabilities are so slow? We should at least check this to see if there is something to fix because in current production it takes no more than 15s for both.

**Comment by tdipisa** [comment]
@randomorder as discussed with the client today, next Thursday, Nov 11 we will have to plan the switch over production at least for the following:

- GeoServers
- MapStore
- Geofence
- GeoWebCache
- GeoNetwork: not yet ready to go in produciton. We will check next week due to some activities still pending for this. this is not a blocker for the other to go live anyway.

**Comment by tdipisa** [comment]
@randomorder I understand, so do you suggest to double check it when it is in production?

**Comment by randomorder** [comment]
thinking

we can do better and use GeoHelthCheck to monitor the response times as long as the machines are accessible from the internet. Do you know if they are / do you have the URLs please?

**Comment by tdipisa** [comment]
@randomorder at the moment the new GSs are not exposed in internet

**Comment by randomorder** [comment]
ok, let close the investigation here for the moment
