### ISSUE TITLE
Embedded error for geostory

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C027#65]
Infinite loading spinner for embedded geostory

**How to Reproduce**
Open [this embedded geostory link](http://sr-vm377-sitms.comune.intranet:8080/mapstore2/geostory-embedded.html#/3066) a
*Current Result**
Infinite loading spinner. Error on console:

> GET http://sr-vm377-sitms.comune.intranet:8080/mapstore2/dist/themes/default.css?SNAPSHOT-6b471a22095c2db72f03e1def12d6d7fd4f9a6af net::ERR_ABORTED 500

**Comment by tdipisa** [comment]
Fixed with #53
