### ISSUE TITLE
Server problem loaded new extension

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2-C027#67]
Loading a new extension requires access to the server

![extension](https://user-images.githubusercontent.com/56537133/134210770-9fcb52bf-5882-4978-a899-7f24e71efc17.gif)

**How to reproduce**
- Open a new contesxt
- Upload [SampleExtension.zip](https://github.com/geosolutions-it/MapStore2-C027/files/7204778/SampleExtension.zip)
- Click on Install

*Current Result**
Access to the server is requested

**Comment by tdipisa** [comment]
Fixed with #73
