### ISSUE TITLE
Corporate proxy issue prevents connections between MS and GN

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#76]
As reported in #72 we should investigate and solve this.

**Comment by tdipisa** [comment]
@lpasquali you have to contact again Carnasciali on the releted email thread:
"problema di connessione tramite proxy comune di firenze tra nuova istanza mapstore e nuova istanza geonetwork"

**Comment by lpasquali** [comment]
@tdipisa done

**Comment by lpasquali** [comment]
@tdipisa @randomorder it looks like that Carnasciali was able to deploy a test application on the mapstore tomcat which is able to honor the proxy configuration, so it looks like that it is mapstore itself to not honor the corporate proxy configuration and make everything through it.
We should also check if other applications at this point have a similare problem connection within other intranet applications (geoserver, geostore)

**Comment by randomorder** [comment]
We need to sort this out @lpasquali. It's been a back and forth for a month now
For MapStore please check with @tdipisa if possible to speak with a GS Proxy person

For the check on GS please do it ASAP. GeoStore should not require internet acceess? I could be wrong

**Comment by tdipisa** [comment]
@randomorder @lpasquali 
I can only say the following:
1. The http-proxy has not been changed and both the MS version currently in production and the new one are using the same verison (v1.1)
2. Also the MS currently in production is not able to reach the [new GN](http://sr-vm378-sitgfn.comune.intranet:9080/geonetwork/srv/ita/csw) and it ias passing through the http-proxy (same version).
3. The MS currently in production is anyway able to reach the [old GN](http://sr-vm107-sitgs1:8080/geonetwork/srv/ita/csw) instance (the current production one) even passing through the proxy

Therefore, could the problem be in the new GN machine or somewhere else? 
GeoStore is not involved here.

**Comment by tdipisa** [comment]
@lpasquali are you working on this today? I'm no longer able to connect MS to the new GN and checking I saw the request passes again through the ms proxy.

**Comment by lpasquali** [comment]
> @lpasquali are you working on this today? I'm no longer able to connect MS to the new GN and checking I have seen the request passes again through the ms proxy.

seeing requests trough the proxy is totally ok, problem is somewhere else between tomcat and their proxy, but I cannot work on this today unfortunately, possibly tomorrow I think

**Comment by lpasquali** [comment]
@tdipisa it looks like is anywat mapstore2 itself to have problem nor the tomcat it is inside of nor the geonetwork instance:

- Firenze sysadmins have setup a very simple "proxy" app on same instance of mapstore2's tomcat which redirects urls you pass it and returns response content in json format:

```
root@sr-vm377-sitms:/var/lib/mapstore2# curl 'http://192.168.202.78:9080/geonetwork/srv/eng/csw?service=CSW&version=2.0.2&request='
<?xml version="1.0" encoding="UTF-8"?>
<response>
  <info>Not a CSW Discovery operation: . Did you mean to use the CSW Publication service? Use service name /csw-publication</info>
</response>

root@sr-vm377-sitms:/var/lib/mapstore2# curl 'http://192.168.202.84:8080/chiamata-bis-demo-0.0.1-SNAPSHOT/chiama?url=http%3A%2F%2Fsr-vm378-sitgfn.comune.intranet%3A9080%2Fgeonetwork%2Fsrv%2Feng%2Fcsw%3Fservice%3DCSW%26version%3D2.0.2%26request%3D'
{"result":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><response>  <info>Not a CSW Discovery operation: . Did you mean to use the CSW Publication service? Use service name /csw-publication</info></response>","content":"http://sr-vm378-sitgfn.comune.intranet:9080/geonetwork/srv/eng/csw?service=CSW&version=2.0.2&request="}
```

**Comment by lpasquali** [comment]
information for further debug:

- http-proxy configuration is the same between old and new environment, we checked with @tdipisa and looks like to be ok
- mapstore should honor these corporate proxy variables:
```
  -Dhttp.proxyHost=proxyhttp.comune.intranet -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxyhttps.comune.intranet -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts='localhost|*.comune.intranet|192.168.*'
```

at the moment, as per @tdipisa request, to permit development proxy is disabled

**Comment by tdipisa** [comment]
@lpasquali thank you so much. The issue is assigned to me now, I will take care of scheduling a debug session as soon as possible.

**Comment by tdipisa** [comment]
@nmco 
we have to schedule a debug session to see why the corporate proxy java_opts are not properly used by the MS http-proxy and do proper fix if needed. 
Can we have someone from the backend Java team to look at this? Maybe Marco Volpini? I'm available for a quick call if needed.

**Comment by randomorder** [comment]
please let us know @nmco

**Comment by randomorder** [comment]
this is a blocker for the release in production

Updates @nmco

**Comment by aaime** [comment]
Been looking into the source code of the [http-proxy project](https://github.com/geosolutions-it/http-proxy).... the proxy code is pretty old, and it's based comons-httpclient 3.x (outdated, the current version is 4, with a completely different API). 

[The system properties that you're trying to pass](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) are honored by the Java own HTTP connection manager, used when opening connections via URL.openConnection. Commons httpclient 3.x is completely ignoring them. The http-proxy code provides support for only two of them:
- ``http.proxyHost``
- ``http.proxyPort``

It means these are completely ignored: ``-Dhttps.proxyHost=proxyhttps.comune.intranet -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts='localhost|*.comune.intranet|192.168.*'``
Mind, the ``https.proxyHost`` has a different value than ``http.proxyHost`` one, so it's really two different routes depending on whether we hare using HTTP or HTTPS... something that commons-httpclient 3 does not support out of the box.
In addition to that, it does not support non proxy hosts either. Mind, it's not impossible to support them, but one has to write quite a bit of code to do so.

We have two choices:
- Write custom code against commons-httpclient 3, to add support for them. To give you an example, [this is code that was present](https://github.com/geotools/geotools/pull/847/files) in GeoTools before the migration to v4, to support the non-proxy hosts. Support for a separate https proxy never landed in GeoTools, so we cannot copy that part.
- Migrate the http-proxy code to commons-httpclient 4, which supports all of the properties above out of the box. Version 4 has a completely different API than v3, but we can look at what modern GeoTools does, and mimick.

In any case, we are not talking about small changes. I'd guesstimate 2.5 days of work, and then we'd need some testing setup with two separate proxies, one for HTTP, one for HTTPS, and a bunch of sites to reach directly (non-proxy hosts).

**Comment by simboss** [comment]
thanks @aaime, let me think about it...

**Comment by tdipisa** [comment]
@simboss @aaime we have the green light from the client to proceed with this implementation using the available support time (4 days of dev/test/pm). Next status meeting has been scheduled for Jan 13. We have agreed to wait for this update deployed and tested before proceeding with the switch over production on Jan (the scheduling to be agreed with the client during the next meeting).

**Comment by simboss** [comment]
@tdipisa I asigned this to @dromagnoli he shall work on it next week the latest.

**Comment by tdipisa** [comment]
@simboss ok thank you for the update

**Comment by tdipisa** [comment]
@simboss @dromagnoli let me know if there is an update on this, at least for the scheduling because next week (Jan 13) I will have the status meeting with the client in the morning.

**Comment by nmco** [comment]
@shadab-geo [THIS](https://github.com/geosolutions-it/http-proxy) is the repository containing the HTTP proxy. [THIS](https://github.com/geosolutions-it/http-proxy/wiki) is the project WIKI documentation.

[THIS](https://github.com/geosolutions-it/MapStore2-C027/issues/76#issuecomment-985637758) is the relevant comment containing @aaime plan. We are going with this option:
```
Migrate the http-proxy code to commons-httpclient 4, which supports all of the properties above out of the box. Version 4 has a completely different API than v3, but we can look at what modern GeoTools does, and mimick.
```

I would suggest the following steps:
1. Get acquainted with the project: build it and run it. Report the problems you may find during the build or what may not be clear.
2. Think about the environment you will need to test your developments, so we can ask DevOps support to set up what we need.
3. Clarify any questions about the scope and the migration to perform.

Some to think about for later since this is a component that needs to be quite performant, we should probably think about the measure | detect performance execution changes (a simple JMeter tests plan?).

**Comment by tdipisa** [comment]
Thank you for the above @nmco. I'm available if something more is needed and I'm looking forward to test in the client environment at the end. @nmco a 1.2 version should be released with a new Tag at the end and the 1.2.x stable branch created accordingly. Master branch should switch to 1.3-SNAPSHOT I think.

**Comment by nmco** [comment]
Good point @tdipisa about versioning, thx!

**Comment by offtherailz** [comment]
Hi, 
from an investigation with @shadab-geo we use http_proxy in MapStore using `war plugin`. War plugin mixes http_proxy and geostore into a single war file. 
We need to update httpclient lib in both http_proxy and geostore, in order to not duplicate libs because of different dependencies.

In particular in GeoStore it is used here: 
https://github.com/geosolutions-it/geostore/blob/110018b03f8f7f7ab8f2be0a3c59b1cedadd9b50/src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/WebServiceTokenAuthenticationFilter.java


MapStore can be tested running in https://github.com/geosolutions-it/MapStore2 `mvn clean install cargo:run -f ./product/pom.xml` and then it will run a tomcat locally to test the proxy at address ,for instance `http://localhost:8080/mapstore/proxy/?url=http://www.google.com`. 

This is the final test you can do to check the proxy is working correctly.

**Comment by tdipisa** [comment]
@nmco Do you have any news on this?

**Comment by nmco** [comment]
Good morning @tdipisa:
- The migration to HTTP Client 4.x is done, @shadab-geo will raise the PR today after lunch, he is finishing implementing a test for the http-proxy properties.
- Two things will still need to be done:
  - A manual test with a real network proxy, do you have an environment to test this?
  - Look at Lorenzo feedback on GeoSotre.

**Comment by nmco** [comment]
Note, our discussion graph: https://docs.google.com/drawings/d/1HRevW3CYcvoMsT-QUCFSVPKVKwVZdLzyZ9tZougbMtQ/edit

**Comment by tdipisa** [comment]
Hi @nmco I haven't see any PR so far from @shadab-geo. Are there trouble with it? Can you please give me an idea of when it will be possible to have it?

**Comment by nmco** [comment]
We are waiting for @shadab-geo to be back and raise the PR which should be ready.

**Comment by shadab-geo** [comment]
PR raised: https://github.com/geosolutions-it/http-proxy/pull/57

**Comment by nmco** [comment]
@shadab-geo I added my first review (well we review it togheter):
https://github.com/geosolutions-it/http-proxy/pull/57

... I made this issue an EPIC and create the other missing tasks (upgrade GeoStore and test this on a real environment).

**Comment by nmco** [comment]
PR https://github.com/geosolutions-it/http-proxy/pull/57 merged.
