### ISSUE TITLE
Export result is empty with GML 3.2 outputFormat 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#79]
Export result file is empty if the outputFormat is GML 3.2

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6441e18d-4fa6-425f-a3fe-97d33cbc5b58)

Sample of request:

curl 'http://sr-vm377-sitms.comune.intranet:8080/mapstore2/proxy/?url=http%3A%2F%2Fsr-vm380-sitgs1.comune.intranet%3A8080%2Fgeoserver%2Fwfs%3Fservice%3DWFS%26outputFormat%3Dgml32%26ms2-authkey%3D70e3e3ae-5229-41e4-b2d9-83b2fcc3c6db' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36' \
  -H 'Content-Type: application/xml' \
  -H 'Origin: http://sr-vm377-sitms.comune.intranet:8080' \
  -H 'Referer: http://sr-vm377-sitms.comune.intranet:8080/mapstore2/' \
  -H 'Accept-Language: en,it;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6' \
  -H 'Cookie: GS_FLOW_CONTROL=GS_CFLOW_-4c1ee9b0:17cb6e5360b:-5c89' \
  --data-raw '<wfs:GetFeature service="WFS" version="1.1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><wfs:Query typeName="celerimetrico:sAlbero_p" ></wfs:Query></wfs:GetFeature>' \
  --compressed \
  --insecure

**Comment by tdipisa** [comment]
Hi @nmco, do you have any news on this?

**Comment by nmco** [comment]
Unfortunately we didn't had time to investigate it @tdipisa, [issue for tracking create on GeoServer side](https://github.com/geosolutions-it/support/issues/1712).

**Comment by ydeliorman** [comment]
GML 3.2 requires wfs 2.0.0. The request body has invalid configurations. After updating the request, an error comes up saying that DB primary key-related errors come up. 

Updated:`version="2.0.0" xmlns:gml="http://www.opengis.net/gml/3.2`

New request:
`curl --location --request POST 'http://sr-vm377-sitms.comune.intranet:8080/mapstore2/proxy/?url=http%3A%2F%2Fsr-vm380-sitgs1.comune.intranet%3A8080%2Fgeoserver%2Fwfs%3Fservice%3DWFS%26outputFormat%3Dgml32%26ms2-authkey%3D70e3e3ae-5229-41e4-b2d9-83b2fcc3c6db' \
--header 'Connection: keep-alive' \
--header 'Accept: application/json, text/plain, /' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36' \
--header 'Content-Type: application/xml' \
--header 'Origin: http://sr-vm377-sitms.comune.intranet:8080' \
--header 'Referer: http://sr-vm377-sitms.comune.intranet:8080/mapstore2/' \
--header 'Accept-Language: en,it;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6' \
--header 'Cookie: GS_FLOW_CONTROL=GS_CFLOW_-4c1ee9b0:17cb6e5360b:-5c89' \
--header 'Authorization: Basic Y3NpdDI1Omdlb3NvbHV0aW9uczIwMjFfMw==' \
--data-raw '<wfs:GetFeature service="WFS" version="2.0.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/2.0.0/wfs.xsd" count="50"><wfs:Query typeNames="celerimetrico:sAlbero_p"></wfs:Query></wfs:GetFeature>'`

Result of the new request
![image](https://user-images.githubusercontent.com/53652228/140891347-276f681c-b9c5-4ccf-afa7-2995fcfaa0ab.png)

Note: as auth in postman, VPN credentials used.

Do you have any idea why is this happening @tdipisa?

**Comment by nmco** [comment]
Next time @ydeliorman please copy paste the actual text, we can't copy paste form an image ... The relevant error is the one starting with "ERROR: relation .... does not exists":
- Why is it complaining about that type?
- Is the original feature type define as an SQL view?
- Can you check the GeoServer configuration @ydeliorman?

**Comment by ydeliorman** [comment]
I do not have the resources to look at those. I cannot access the logs.

- I will be needing to check logs in order to have a better inside for that.
- How can I check that?
- The user that I currently have the credentials for (in the SS), does not have the auth to look that.

Also, for better investigation, DB configurations could be shared since an error might be related to DB.

![image](https://user-images.githubusercontent.com/53652228/141060343-e6a02c31-8cf2-4782-afc2-06216871d680.png)

**Comment by tdipisa** [comment]
@nmco @ydeliorman thank you.
I've tried with another dataset _sivep:aree_verdi_ 

`<wfs:GetFeature service="WFS" version="2.0.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/2.0.0/wfs.xsd"><wfs:Query typeName="sivep:aree_verdi" ></wfs:Query></wfs:GetFeature>`

and I got the same error:

```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://datigisnew.comune.intranet/geoserver/schemas/ows/1.1.0/owsAll.xsd?ms2-authkey=70c8ce4d-3bdc-45cb-ab4d-4889586dfd7a">
    <ows:Exception exceptionCode="NoApplicableCode">
        <ows:ExceptionText>java.lang.RuntimeException: java.io.IOException: Error looking up primary key
java.io.IOException: Error looking up primary key
Error looking up primary key
ERROR: relation &amp;quot;unesco.v_d612_scheda_ouv_geo&amp;quot; does not exist
  Position: 144</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

I don't know why to be honest, anyway this issue is not to investigate about data. I think the following is enough for now since MS doesn't support yet WFS 2.0.0:

>GML 3.2 requires wfs 2.0.0. The request body has invalid configurations.
