### ISSUE TITLE
Enable WFS-T in the new SDI

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#84]
The client is asking to enable the WFS-T only in the **NEW** SDI for both GS clusters.

https://docs.geoserver.org/latest/en/user/services/wfs/webadmin.html

**Comment by lpasquali** [comment]
@tdipisa all 4 geoserver instances have WFS-T enabled since now

**Comment by tdipisa** [comment]
@lpasquali thank you, I'm going to inform the client.
