### ISSUE TITLE
New custom Tile Provider as default

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#99]
From the client we have this request:

>su richiesta di Emanuele di mettere nuovi sfondi in mapstore2 (ad esempio le ciclabili da OSM), ho guardato la documentazione di mapstore2 ma non so se ho trovato il punto giusto..

>Qui:

>https://mapstore2.readthedocs.io/en/dev_guide/developer-guide/maps-configuration/#providers-and-variants

>si legge che è possibile aggiungere dei provider di tipo 'tileprovider' (anziché osm) e ho visto che nel new.json attuale esiste lo sfondo di opentopomap così specificato:

```
      {
        "type": "tileprovider",
        "title": "OpenTopoMap",
        "provider": "OpenTopoMap",
        "name": "OpenTopoMap",
        "source": "OpenTopoMap",
        "group": "background",
        "visibility": false
      }
```

>Esiste una lista di tipologie di provider supportate in mapstore2? Perché ho provato a fare una cosa analoga:

```
      {
        "type": "tileprovider",
        "title": "OpenCycleMap",
        "provider": "OpenCycleMap",
        "name": "OpenCycleMap",
        "source": "OpenCycleMap",
        "group": "background",
        "visibility": false
      },
```

>al momento che esiste opencyclemap.org , ma mapstore2 si è bloccato perché immagino non trova una definizione per il provider che ho messo.

>Io avevo provato ad aggiungere da interfaccia il servizio delle ciclabili come sfondo, pescandolo da un catalogo che ho definito di tipo tms e ha come url : "https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png" e questo funziona, come si vede dalla mappa :
http://sr-vm377-sitms:8080/mapstore2/#/viewer/openlayers/3972

>Questo però chiaramente mi funziona solo nella mappa suddetta.

>Quindi, per mettere nuove mappe di sfondo sul new.json , va cercata una definizione dei provider (o aggiornata da qualche parte in mapstore2) o dovrei ricorrere ai tms (di cui non ho trovato un esempio) ?

**Comment by offtherailz** [comment]
In the documentation you linked there is a list of currently pre-defined services where to select from. 

You can use one of them adding to the "provider" string from the list provided in documentation. Example:
```
{             
                "group": "background",
                "provider": "Thunderforest.OpenCycleMap",
                "title": "OpenCycleMap",
                "type": "tileprovider",
                "visibility": true
            }
```
![image](https://user-images.githubusercontent.com/1279510/155158643-41714c7e-5048-4dda-9b18-469d661adfa8.png)

The "provider" entry is in form "<name>.<variant>".  

Anyway they are only presets. Actually some of the providers listed may be not be updated. Some of them may be dismissied, some other require an api-key.

You can configure tileproviders of any kind simply adding the "provider": "custom" and "url" with the template as you did. The options available are the same. example: 

```
   {
                "provider": "custom",
                "title": "test",
                "type": "tileprovider",
                "url": "https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png",
                "visibility": true
            }
```

_note: At the moment we don't support api-key centralization for the application. You can specify them in the URL, but they will be saved in maps, and so updating them may mean to update every map_
